name: Deploy to Ubuntu Server

on:
 workflow_run:
    workflows: ["Build and Push Docker Image"]  # Name of your build workflow
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
    
          if [ ! -d ~/support-ticket-mlops ]; then
            git clone git@github.com:karthik0517-rgt/support-ticket-mlops.git ~/support-ticket-mlops
          fi
    
          cd ~/support-ticket-mlops
          git pull origin main
    

          docker stop support-app || true
          docker rm support-app || true
          
          docker pull karthik0517/support-ticket-zero-shot:latest
          
          docker run -d -p 8000:8000 \
            -v ~/model_cache:/app/model_cache \
            -e HF_HOME=/app/model_cache \
            --name support-app karthik0517/support-ticket-zero-shot:latest
        EOF
    
